<?php
namespace devmustafa\blog\modules\frontend\controllers;

use Yii;
use yii\web\Controller;
use yii\data\Pagination;
use devmustafa\blog\models\Post;

/**
 * Site controller
 */
class PostController extends Controller
{
    /**
     * @var int
     */
    public $module;

    /**
     * @var int
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->module = Yii::app()->getModule('blog');
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actionIndex()
    {
        // get page
        $page_size = $this->page_size;
        $page_number = Yii::$app->request->get('page', 1);
        $page_number -= 1; // get the real page number

        $q = Yii::$app->request->get('q', '');

        // return query object
        $query = (new Post)->getPostsList($page_number, $page_size, $q);

        $posts = $query->all();

        $pages = new Pagination([
            'totalCount' => $query->count(),
            'defaultPageSize' => $page_size,
            'pageSize' => $page_size,
            'route' => '/post',
        ]);

        return $this->render('index', [
            'posts' => $posts,
            'pages' => $pages,
        ]);
    }

    /**
     * @inheritdoc
     */
    public function actionSingle()
    {
        // get slug
        $slug = Yii::$app->request->get('slug');

        // return query object
        $query = (new Post)->getSinglePost($slug);

        $post = $query->one();
        // die(print_r($post));

        return $this->render('single', [
            'post' => $post,
        ]);
    }

}
